### ISSUE TITLE
wLaunchElf can't handle all the config files transferred at once.

### ISSUE THREAD

**Issue by ghost** [Tom-Bruise/PS2-OPL-CFG#5]
Not really anything wrong with your tool per say, but I think you should note on the instructions page that uLaunchElf absolutely cannot handle transferring all 14k config files at once from a USB. It will do at least 500 or so, then fail/cancel without warning.

**Comment by micbuffa** [comment]
So what is the best way to install all 14k files ? transfer them 500 by 500 or less at the same time ?

**Comment by micbuffa** [comment]
Does the last wLaunchElf has the same problem?

**Comment by ghost** [comment]
I don't know what wLaunchElf is, but the latest uLaunchElf has this problem. I'd say 500 at a time would be a safe number. Don't even try to FTP that many, PS2Net is so terrible that it really can't handle it.

**Comment by micbuffa** [comment]
Ok, I split all the files into sub folders of 500 files using this line of shell script (I'm on a Mac) : 
cd CFG_fr
ls|parallel -n500 mkdir {#}\;mv {} {#}

this created 28 subfolders named 1, 2, 3 ... 28, each containing 500 cfg files, then I copied all these to a USB key, and using wLaunchElf I started to copy them 500 by 500. It takes some time but apparently it works.

Once there was LauchElf and the devs stopped maintaining it
Then there was the "unofficial" uLaunchElf maintained by new developers who then retired too
Then there is the "unofficial unofficial wLaunchElf" with new devs. u+u = uu that looks like a w :-)

**Comment by ghost** [comment]
Interesting, I'll have to give this a try. This is kinda a pain in the ass though. It would be nice if WLaunchElf wasn't broken (yes, I was using wLaunchElf), or if we could get a homebrew script to do this automatically.

I've reported the issue here:
https://github.com/ps2homebrew/wLaunchELF/issues/48

I guess this thread can be closed, unless the author wants to make some type of homebrew script to make this process easier.

**Comment by Tom-Bruise** [comment]
I did experience this problem myself, and I included [this script](https://github.com/Tom-Bruise/PS2-OPL-CFG-Database/blob/master/scripts/export_cfg_from_csv.sh) to export only the relevant CFG files given a game list produced with OPL Manager.

Thanks for filing the bug with wLaunchELF folks. I will add a note in the readme.

Closing this one!

**Comment by xKuruh** [comment]
> Ok, I split all the files into sub folders of 500 files using this line of shell script (I'm on a Mac) : cd CFG_fr ls|parallel -n500 mkdir {#};mv {} {#}
> 
> this created 28 subfolders named 1, 2, 3 ... 28, each containing 500 cfg files, then I copied all these to a USB key, and using wLaunchElf I started to copy them 500 by 500. It takes some time but apparently it works.
> 
> Once there was LauchElf and the devs stopped maintaining it Then there was the "unofficial" uLaunchElf maintained by new developers who then retired too Then there is the "unofficial unofficial wLaunchElf" with new devs. u+u = uu that looks like a w :-)

"For windows users"
I also did the same but with windows Powershell
Just Copy this into a txt file change your source/destination folder and save it as a ".ps1" file right click "Run with Powershell" done

```
# Change these as preferred
$sourceFolder = "C:\Downloads\ps2 stuff\CFG_en"
$destinationRoot = "C:\Downloads\ps2 stuff\CFG_en"
$extensions = @("*.cfg")
$itemsPerFolder = 500

$allItems = @(Get-ChildItem $sourceFolder -Include $extensions -Recurse)
for ($i = 0; $i -lt $allItems.Count; $i++)
{
    $folder = [math]::Floor($i / $itemsPerFolder)
    $tDest = "$destinationRoot\$folder"
    if (!(Test-Path $tDest))
    {
        mkdir $tDest
    }
    Move-Item $allItems[$i] -Destination $tDest
}
```
[500 Per Folder.zip](https://github.com/Tom-Bruise/PS2-OPL-CFG-Database/files/10339389/500.Per.Folder.zip)
